version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
    - image: circleci/node:10-browsers # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
    - checkout # special step to check out source code to working directory
    - restore_cache: # special step to restore the dependency cache
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: install dependencies
        command: yarn
    - save_cache: # special step to save the dependency cache
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - ./node_modules
    - run: # check that builds properly
        name: build
        command: yarn build
    - run: # check that the project is linted properly
        name: lint
        command: yarn lint
    - run: # run unit tests
        name: unit tests
        command: yarn test:unit
